"""Prompt templates for TNL phases."""

from .templates import (
    SYSTEM_PROMPT,
    ONBOARDING_WELCOME,
    CHARACTER_CREATION_PROMPT,
    CHARACTER_SUMMARY_PROMPT,
    WORLD_CHUNK_PROMPTS,
    GAMEPLAY_SYSTEM_PROMPT,
    GAMEPLAY_RESPONSE_PROMPT,
    CAMPAIGN_INTRO_PROMPT,
    build_intro_prompt,
)

__all__ = [
    "SYSTEM_PROMPT",
    "ONBOARDING_WELCOME",
    "CHARACTER_CREATION_PROMPT",
    "CHARACTER_SUMMARY_PROMPT",
    "WORLD_CHUNK_PROMPTS",
    "GAMEPLAY_SYSTEM_PROMPT",
    "GAMEPLAY_RESPONSE_PROMPT",
    "CAMPAIGN_INTRO_PROMPT",
    "build_intro_prompt",
]
